/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as ContractPreviewRouteImport } from './routes/contract-preview'
import { Route as CoffeeRouteImport } from './routes/coffee'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FactoryStepRouteImport } from './routes/factory.$step'

const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractPreviewRoute = ContractPreviewRouteImport.update({
  id: '/contract-preview',
  path: '/contract-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeRoute = CoffeeRouteImport.update({
  id: '/coffee',
  path: '/coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryStepRoute = FactoryStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => FactoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coffee': typeof CoffeeRoute
  '/contract-preview': typeof ContractPreviewRoute
  '/factory': typeof FactoryRouteWithChildren
  '/features': typeof FeaturesRoute
  '/factory/$step': typeof FactoryStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coffee': typeof CoffeeRoute
  '/contract-preview': typeof ContractPreviewRoute
  '/factory': typeof FactoryRouteWithChildren
  '/features': typeof FeaturesRoute
  '/factory/$step': typeof FactoryStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coffee': typeof CoffeeRoute
  '/contract-preview': typeof ContractPreviewRoute
  '/factory': typeof FactoryRouteWithChildren
  '/features': typeof FeaturesRoute
  '/factory/$step': typeof FactoryStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coffee'
    | '/contract-preview'
    | '/factory'
    | '/features'
    | '/factory/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coffee'
    | '/contract-preview'
    | '/factory'
    | '/features'
    | '/factory/$step'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coffee'
    | '/contract-preview'
    | '/factory'
    | '/features'
    | '/factory/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoffeeRoute: typeof CoffeeRoute
  ContractPreviewRoute: typeof ContractPreviewRoute
  FactoryRoute: typeof FactoryRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract-preview': {
      id: '/contract-preview'
      path: '/contract-preview'
      fullPath: '/contract-preview'
      preLoaderRoute: typeof ContractPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee': {
      id: '/coffee'
      path: '/coffee'
      fullPath: '/coffee'
      preLoaderRoute: typeof CoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory/$step': {
      id: '/factory/$step'
      path: '/$step'
      fullPath: '/factory/$step'
      preLoaderRoute: typeof FactoryStepRouteImport
      parentRoute: typeof FactoryRoute
    }
  }
}

interface FactoryRouteChildren {
  FactoryStepRoute: typeof FactoryStepRoute
}

const FactoryRouteChildren: FactoryRouteChildren = {
  FactoryStepRoute: FactoryStepRoute,
}

const FactoryRouteWithChildren =
  FactoryRoute._addFileChildren(FactoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoffeeRoute: CoffeeRoute,
  ContractPreviewRoute: ContractPreviewRoute,
  FactoryRoute: FactoryRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
